## **Hyper parameter tuning**
Hyperparameter tuning (or hyperparameter optimization) is the process of determining the right combination of hyperparameters that maximizes the model performance. It works by running multiple trials in a single training process.

In [18]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [19]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [20]:
digits=load_digits()
df= pd.DataFrame(digits.data)
df

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

### **GridSearchCV**

In [21]:
from sklearn.model_selection import GridSearchCV
gridSearch = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)

gridSearch.fit(digits.data, digits.target)
gridSearch.cv_results_

{'mean_fit_time': array([0.28689079, 0.02463589, 0.36198516, 0.03971438, 0.35462637,
        0.02520347]),
 'mean_score_time': array([0.05729289, 0.00642457, 0.07895365, 0.0094275 , 0.07913728,
        0.00642414]),
 'mean_test_score': array([0.44854534, 0.94769731, 0.47636645, 0.94769731, 0.47636645,
        0.94769731]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'rank_test_score': array([6, 1, 4, 1, 4, 1], dtype=int32),
 'split0_test_score': array([0.41111111, 0.96388889, 0.45277778, 0.96388889, 0.45277778,
        0.96388889]),
 'split1_test_score': array([0.45      , 0.91944444, 0.46944444, 0.91944444, 0.46944444,
        0.91944444]),
 'split2_test_score': array([0.454039  , 0.96657382, 0.47910864, 0.96657382, 0.47910864,
        0.96657382]),
 'split3_test_score': array([0.44846797, 0.9637883 , 0.47910864, 0.9637883 , 0.47910864,
        0.9637883 ]),
 'split4_test_score': array([0.47910864, 0.92479109, 0.50139276, 0.92479109, 0.50139276,
        0.92479109]),
 'std_fit_time': array([0.00455937, 0.00119046, 0.07656977, 0.00707322, 0.07568905,
        0.00246215]),
 'std_score_time': array([2.33048003e-03, 9.15898059e-05, 1.90013466e-02, 1.52513216e-03,
        1.63337613e-02, 2.06602453e-04]),
 'std_test_score': array([0.02176115, 0.02097775, 0.01578414, 0.02097775, 0.01578414,
        0.02097775])}

In [22]:
results = pd.DataFrame(gridSearch.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.286891,0.004559,0.057293,0.002330,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.411111,0.450000,0.454039,0.448468,0.479109,0.448545,0.021761,6
1,0.024636,0.001190,0.006425,0.000092,1,linear,"{'C': 1, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
2,0.361985,0.076570,0.078954,0.019001,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,4
3,0.039714,0.007073,0.009427,0.001525,10,linear,"{'C': 10, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1
4,0.354626,0.075689,0.079137,0.016334,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.452778,0.469444,0.479109,0.479109,0.501393,0.476366,0.015784,4
5,0.025203,0.002462,0.006424,0.000207,20,linear,"{'C': 20, 'kernel': 'linear'}",0.963889,0.919444,0.966574,0.963788,0.924791,0.947697,0.020978,1

In [23]:
results[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.448545
1       1       linear         0.947697
2      10          rbf         0.476366
3      10       linear         0.947697
4      20          rbf         0.476366
5      20       linear         0.947697

In [24]:
gridSearch.best_params_

{'C': 1, 'kernel': 'linear'}

In [25]:
gridSearch.best_score_

0.9476973073351903

### **Using GridSearchCV for all classification models and each or their parameters at once using function.**

In [26]:
model_params = {
    
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : { 'C': [1,5,10], 'kernel': ['rbf','linear']
        }  
    },
   
    'random_forest': {'model': RandomForestClassifier(), 
                      'params' : {'n_estimators': [1,4,9]
        }
    },
  
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {'C': [1,5,10]
        }
    },
   
    'decision_tree': {
        'model': DecisionTreeClassifier(),
        'params': {'criterion': ['gini','entropy']
        },


    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params': {}
    },

    'naive_bayes_multinomial': {
        'model': MultinomialNB(),
        'params': {}
    }
    }     
}

In [27]:
from sklearn.model_selection import GridSearchCV
scores = []

In [28]:
for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [29]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                 model  best_score                   best_params
0                  svm    0.947697  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.887055           {'n_estimators': 9}
2  logistic_regression    0.922114                      {'C': 1}
3        decision_tree    0.817491      {'criterion': 'entropy'}

### **SVM gave the best result with parameters {'C': 1, 'kernel': 'linear'}**